name: Build Godot Templates

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Godot Version'
        required: true
        type: string
        default: '4.5'
      platforms:
        description: "List of platforms"
        default: 'linux windows web'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      platforms: ${{ steps.generate-matrix.outputs.platforms }}
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          platforms=$(echo '"${{ inputs.platforms }}"' | jq -c '. | split(" ") | map(select(length > 0))')
          echo "platforms=$platforms" >> $GITHUB_OUTPUT

  template-build:
    runs-on: ubuntu-latest
    needs: init
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.init.outputs.platforms) }}
    steps:
      - uses: kuma-gee/action-godot-template@master
        with:
          version: ${{ inputs.version }}
          platform: ${{ matrix.platform }}
          encryption-key: ${{ secrets.ENCRYPTION_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: template-${{ matrix.platform }}
          path: custom_templates/
          if-no-files-found: error

  release-godot-template:
    runs-on: ubuntu-latest
    needs: template-build
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: template-*
          path: bin
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          files: bin/*
          name: Godot ${{ inputs.version }} Templates
          tag_name: template-${{ inputs.version }}